riddlebase/urls.py
from django.contrib import admin
from django.urls import include, path

import riddles.urls
from base.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('riddles/', include(riddles.urls)),
]

riddles/urls.py
from django.urls import include, path


from . import views

app_name = 'riddles'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:pk>/', views.category, name='category'),
    path('type/<int:pk>/', views.riddle_type, name='type'),
    path('riddle/<int:pk>/', views.riddle, name='riddle'),
    path('riddle/<int:pk>/check/', views.check, name='check'),
]

sudoku/urls.py
from django.conf.urls import url

from . import views

app_name = 'sudoku'

urlpatterns = [
    url(r'^$', views.view_index, name='index'),
    url(r'^(?P<riddle_id>[0-9]+)/$', views.view_riddle, name='riddle'),
    url(r'^(?P<riddle_id>[0-9]+)/check/$', views.rest_check, name='check'),
    url(r'^create/$', views.view_creator, name='creator'),
    url(r'^submit-new/$', views.rest_create, name='create'),
]

riddles/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from riddles import util


class RiddleCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
    description = models.TextField()

    def clean(self):
        if self.parent == self:
            raise ValidationError('You cannot set the parent to the object itself.')

    def __str__(self):
        return self.name


class RiddleType(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    category = models.ForeignKey(RiddleCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Riddle(models.Model):
    riddle_type = models.ForeignKey(RiddleType, on_delete=models.CASCADE)
    solution = models.CharField(max_length=1000)
    pattern = models.CharField(max_length=1000)
    difficulty = models.PositiveSmallIntegerField(blank=True, null=True, validators=[
        MinValueValidator(1),
        MaxValueValidator(10)])
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    def previous_pk(self):
        previous_set = Riddle.objects.filter(pk__lt=self.pk).order_by('-pk')
        return previous_set[0].pk if previous_set else None

    def next_pk(self):
        next_set = Riddle.objects.filter(pk__gt=self.pk).order_by('pk')
        return next_set[0].pk if next_set else None

    def clean(self):
        pat_len = len(self.pattern)
        sol_len = len(self.solution)
        if pat_len != sol_len:
            raise ValidationError('Pattern length does not match solution length.')
        if not util.is_square(pat_len):
            raise ValidationError('Riddle value length is not square.')

    def get_or_create_state(self, user: User) -> str:
        state_values = self.pattern
        if user.is_authenticated():
            try:
                state = self.riddlestate
                state_values = state.values
            except ObjectDoesNotExist:
                state = RiddleState(user=user, riddle=self, values=self.pattern)
                state.save()
                state_values = state.values
        return state_values

    def __str__(self):
        return f"{self.riddle_type.name} {self.pk}"


class RiddleState(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    riddle = models.ForeignKey(Riddle, on_delete=models.CASCADE)
    value = models.TextField()
    modified_on = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "riddle")

    def __str__(self) -> str:
        return f"{self.riddle.riddle_type.name} {self.riddle.pk} {self.user.name}"

sudoku/models.py
import math

from django.core.validators import MinValueValidator
from django.db import models

from riddles.models import Riddle


class Sudoku(models.Model):
    riddle = models.OneToOneField(Riddle, on_delete=models.CASCADE)
    box_rows = models.IntegerField(verbose_name='Number of horizontal box-rows', validators=[
        MinValueValidator(2)])

    @property
    def cells(self) -> int:
        return len(self.riddle.solution)

    @property
    def size(self) -> int:
        return int(math.sqrt(self.cells))

    @property
    def solution_as_list(self) -> list:
        return list(self.riddle.solution)

    @property
    def pattern_as_list(self) -> list:
        return list(self.riddle.pattern)

    @property
    def solution_as_two_dimensional_array(self) -> list:
        array = []
        for row_i in range(self.size):
            cell_i = row_i * self.size
            row = list(self.riddle.solution[cell_i:cell_i + self.size])
            array.append(row)
        return array

    @staticmethod
    def check_solution(pattern, solution) -> bool:
        raise NotImplementedError

    def __str__(self) -> str:
        return "Sudoku: {}".format(self.pk)

riddles/views.py
import datetime

from django.conf import settings
from django.http import Http404, HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .models import Riddle, RiddleCategory, RiddleType


def index(request: HttpRequest) -> HttpResponse:
    return render(request, 'riddles/index.html')


def category(request: HttpRequest, pk: int) -> HttpResponse:
    riddle_category = get_object_or_404(RiddleCategory, pk=pk)
    return render(request, 'riddles/category.html', {
        "category": riddle_category,
    })


def riddle_type(request: HttpRequest, pk: int) -> HttpResponse:
    _riddle_type = get_object_or_404(RiddleType, pk=pk)
    return render(request, 'riddles/type.html', {
        "riddle_type": _riddle_type,
    })


def riddle(request: HttpRequest, pk: int) -> HttpResponse:
    riddle = get_object_or_404(Riddle, pk=pk)
    context = {
        'riddle': riddle,
        'previous': Riddle.objects.filter(pk__lt=pk).order_by('pk').last(),
        'next': Riddle.objects.filter(pk__gt=pk).order_by('pk').first(),
    }

    state = request.POST.get('state', request.session.get('state', riddle.pattern))
    if request.POST.get('revert'):
        state = riddle.pattern
    request.session['state'] = state
    context['state'] = state

    if state == riddle.solution:
        context['correct'] = True

    if request.POST.get('submit'):
        if state != riddle.solution:
            context['incorrect'] = True

    return render(request, 'riddles/riddle.html', context)


@csrf_exempt
@require_POST
def check(request: HttpRequest, pk: int) -> JsonResponse:
    riddle = get_object_or_404(Riddle, pk=pk)

    state = request.POST.get("state")
    correct = state == riddle.solution
    response = {'correct': correct}
    return JsonResponse(response)

sudoku/views.py
from django.http import Http404, HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from riddles.models import Riddle
from sudoku.models import Sudoku


def view_index(request) -> HttpResponse:
    return render(request, 'sudoku/index.html', {
        'pks': list(sudoku.pk for sudoku in Riddle.objects.filter(riddle_type__name='sudoku')),
    })


def view_riddle(request: HttpRequest, sudoku_number: int) -> HttpResponse:
    try:
        sudoku = Sudoku.objects.get(pk=sudoku_number)
    except Riddle.DoesNotExist:
        raise Http404("Sudoku does not exist")

    context = sudoku.riddle.get_context(request.user)
    context.update({
        'box_rows': sudoku.box_rows,
    })
    return render(request, 'sudoku/riddle.html', context)


def view_creator(request: HttpRequest) -> HttpResponse:
    return render(request, 'sudoku/creator.html')


@csrf_exempt
@require_POST
def rest_check(request: HttpRequest, riddle_id: int) -> JsonResponse:
    try:
        sudoku = Sudoku.objects.get(pk=riddle_id)
    except Sudoku.DoesNotExist:
        raise Http404("Sudoku does not exist")

    proposal = request.POST.get("proposal")
    correct = proposal is not None and proposal == sudoku.solution
    response = {'correct': correct}
    return JsonResponse(response)


@require_POST
def rest_create(request: HttpRequest) -> JsonResponse:
    error = []
    if not request.user.has_perm("riddles.add_sudoku"):
        error.append("no permission")

    solution = request.POST.get("solution")
    pattern = request.POST.get("pattern")

    if solution is None:
        error.append("no solution")
    if pattern is None:
        error.append("no pattern")

    if error:
        return JsonResponse({'error': error})

    riddle = Riddle(solution=solution,
                    pattern=pattern,
                    state=pattern,
                    difficulty=5,
                    box_rows=3)
    riddle.save()
    return JsonResponse({'pk': riddle.pk})

riddles/templates/riddles/category.html
{% extends 'base.html' %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
<h1>{{ category.name }}</h1>
<ul>
    {% for riddle_type in category.riddletype_set.all %}
    <li><a href="{% url 'riddles:type' riddle_type.pk %}">{{ riddle_type.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

riddles/templates/riddles/riddle.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ riddle.riddle_type.name }} {{ riddle.pk }}{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'riddles/css/riddle.css' %}">
{% endblock styles %}

{% block content %}
<a href="{% url 'riddles:category' riddle.riddle_type.category.pk %}">{{ riddle.riddle_type.category.name }}</a><br />
<a href="{% url 'riddles:type' riddle.riddle_type.pk %}">{{ riddle.riddle_type.name }}</a>
<h1>{{ riddle.riddle_type.name }} {{ riddle.pk }}</h1>
<a {% if previous %}href="{% url 'riddles:riddle' previous.pk %}" {% endif %}>&lt;&lt;</a>
<a {% if next %}href="{% url 'riddles:riddle' next.pk %}" {% endif %}>&gt;&gt;</a>
<form method="post" class="{% if incorrect %}incorrect{% endif %}{% if correct %}correct{% endif %}">
    {% csrf_token %}
    <input type="hidden" name="state" id="state" value="{{ state }}" />
    <input type="submit" name="submit" value="submit" />
    <input type="submit" name="revert" value="revert" />
</form>

<div>
    <button id="shrink">shrink</button>
    <button id="restore-size">restore-size</button>
    <button id="enlarge">enlarge</button>
    <button id="full-screen">full-screen</button>
</div>

<svg id="riddle" shape-rendering="crispEdges">
    <g id="riddle-values"></g>
    <g id="riddle-grid">
        <g id="riddle-grid-thin"></g>
        <g id="riddle-grid-bold"></g>
    </g>
    <g id="picker">
        <rect id="picker-background" x="0" y="0" width="0" height="0"></rect>
        <g id="picker-values"></g>
        <g id="picker-grid">
            <g id="picker-grid-inner"></g>
            <g id="picker-grid-outer"></g>
        </g>
    </g>
</svg>
{% endblock %}

{% block endscripts %}
{{ block.super }}
<script type="module">
    import * as RiddleManager from '{% static "riddles/js/riddle-manager.js" %}'
    import * as Riddle from '{% static "riddles/js/sudoku.js" %}'
    Riddle.init("{{ riddle.pattern }}", "{{ state }}");
    RiddleManager.init();
    RiddleManager.adjustViewBox();
    RiddleManager.resetZoom();

</script>
{% endblock %}

riddles/templates/riddles/sudoku-creator.html
{% extends 'base.html' %}
{% load static %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static 'riddles/js/sudoku-creator.js' %}"></script>
{% endblock %}
{% block title %}Sudoku Creator{% endblock %}
{% block body %}
    <h1>Sudoku Creator</h1>
    <div class="container">
        <form class="gap-bot">
            <div class="form-group row">
                <label class="col-sm-2 form-control-label" for="input-box-rows">Box Rows</label>
                <div class="col-sm-10">
                    <input id="input-box-rows" name="input-box-rows" type="number" min="2" placeholder="Box Columns">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 form-control-label" for="input-box-columns">Box Columns</label>
                <input id="input-box-columns" name="input-box-columns" type="number" min="2" placeholder="Box Columns">
            </div>
            <div class="form-group row">
                <button id="create" class="btn btn-primary">Create Grid</button>
            </div>
        </form>
        <div class="gap-bot row">
            <button class="btn btn-default" id="shrink"><span class="glyphicon glyphicon-zoom-out"></span></button>
            <button class="btn btn-default" id="restore-size"><span class="glyphicon glyphicon-search"></span></button>
            <button class="btn btn-default" id="enlarge"><span class="glyphicon glyphicon-zoom-in"></span></button>
            <button class="btn btn-default" id="full-screen"><span class="glyphicon glyphicon-fullscreen"></span>
            </button>
        </div>
        <div class="row gap-bot">
            <svg id="riddle" shape-rendering="crispEdges">
                <g id="riddle-values"></g>
                <g id="riddle-grid">
                    <g id="riddle-grid-thin"></g>
                    <g id="riddle-grid-bold"></g>
                </g>
                <g id="picker">
                    <rect id="picker-background" x="0" y="0" width="0" height="0"></rect>
                    <g id="picker-values"></g>
                    <g id="picker-grid">
                        <g id="picker-grid-inner"></g>
                        <g id="picker-grid-outer"></g>
                    </g>
                </g>
            </svg>
        </div>
        <div class="row">
            <button id="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
{% endblock %}
{% block endscripts %}
    <script>
        Creator.init("{{ csrf_token }}");
    </script>
{% endblock %}

riddles/templates/riddles/sudoku.html
{% extends 'riddles/riddle.html' %}
{% load staticfiles %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static 'riddles/js/sudoku.js' %}"></script>
{% endblock %}
{% block initriddle %}
    <script>
        Riddle.init("{{ pattern }}", "{{ state }}", {{ box_rows }});
    </script>
{% endblock %}

riddles/templates/riddles/type.html
{% extends 'base.html' %}

{% block title %}{{ riddle_type.name }}{% endblock %}

{% block content %}
<a href="{% url 'riddles:category' riddle_type.category.pk %}">{{ riddle_type.category.name }}</a>
<h1>{{ riddle_type.name }}</h1>
<ul>
    {% for riddle in riddle_type.riddle_set.all %}
    <li><a href="{% url 'riddles:riddle' riddle.pk %}">{{ riddle.pk }}</a></li>
    {% endfor %}
</ul>
{% endblock %}