riddlebase/urls.py
from django.contrib import admin
from django.urls import include, path

import riddles.urls
from base.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('riddles/', include(riddles.urls)),
]

riddles/urls.py
from django.urls import include, path


from . import views

app_name = 'riddles'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:pk>/', views.category, name='category'),
    path('type/<int:pk>/', views.riddle_type, name='type'),
    path('riddle/<int:pk>/', views.riddle, name='riddle'),
    path('riddle/<int:pk>/check/', views.check, name='check'),
]

sudoku/urls.py
from django.conf.urls import url

from . import views

app_name = 'sudoku'

urlpatterns = [
    url(r'^$', views.view_index, name='index'),
    url(r'^(?P<riddle_id>[0-9]+)/$', views.view_riddle, name='riddle'),
    url(r'^(?P<riddle_id>[0-9]+)/check/$', views.rest_check, name='check'),
    url(r'^create/$', views.view_creator, name='creator'),
    url(r'^submit-new/$', views.rest_create, name='create'),
]

templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block body %}
    <h1>Home</h1>
    <a href="{% url 'riddles:index' %}">Riddles</a>
{% endblock %}

templates/navbar.html
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">RiddleBase</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a class="dropdown-toggle"
                           data-toggle="dropdown" href="{% url 'riddles:index' %}">Riddles <span
                            class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'riddles:sudoku:index' %}">Sudoku</a></li>
                            <li><a href="{% url 'riddles:slither:index' %}">Slither</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>